# tasks file for php-56-cli
---
#- name: php | configuration | update /etc/php5/apache2/php.ini
#  template:
#    src: etc/php5/apache2/php.ini.j2
#    dest: /etc/php5/apache2/php.ini
#    owner: root
#    group: root
#    mode: 0644
#  notify: reload apache2
#  tags:
#    - configuration
#    - php-56-cli
#    - php-56-cli-php
#    - php-56-cli-php-configuration
#    - php-56-cli-php-configuration-general
