# tasks file
---
- name: configuration | update alternatives
  community.general.alternatives:
    name: php
    path: "/usr/bin/php{{ php_56_cli_version }}"
  when: php_56_cli_update_alternatives | bool
  tags:
    - configuration
    - php-56-cli
    - php-56-cli-configuration
    - php-56-cli-configuration-update-alternatives

- name: configuration | update php.ini
  ansible.builtin.template:
    src: "{{ php_56_cli_configuration_file.lstrip('/') }}.j2"
    dest: "{{ php_56_cli_configuration_file }}"
    owner: root
    group: root
    mode: 0644
  tags:
    - configuration
    - php-56-cli
    - php-56-cli-configuration
    - php-56-cli-configuration-general
