# tasks file for php-56-cli
---
- name: install | dependencies
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ php_56_cli_dependencies }}"
  tags:
    - configuration
    - php-56-cli
    - php-56-cli-install
    - php-56-cli-install-dependencies

- name: install | additional
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ php_56_cli_install }}"
  tags:
    - configuration
    - php-56-cli
    - php-56-cli-install
    - php-56-cli-install-additional
