# tasks file
---
- name: install | dependencies
  ansible.builtin.apt:
    name: "{{ php_56_cli_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - configuration
    - php-56-cli
    - php-56-cli-install
    - php-56-cli-install-dependencies

- name: install | additional
  ansible.builtin.apt:
    name: "{{ php_56_cli_install }}"
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - configuration
    - php-56-cli
    - php-56-cli-install
    - php-56-cli-install-additional
