# tasks file
---
- name: mods | install
  ansible.builtin.apt:
    name: "{{ item.value.dependencies | default(php_56_cli_mods_dependencies[item.key]) | default([]) }}"
    state: "{{ apt_install_state | default('latest') }}"
  with_dict: "{{ php_56_cli_mods_present }}"
  tags:
    - configuration
    - php-56-cli
    - php-56-cli-mods
    - php-56-cli-mods-install
