# tasks file
---
- name: mods | touch priorities
  ansible.builtin.copy:
    content: ''
    dest: "{{ php_56_cli_mods_available_path }}/{{ item }}.ini"
    force: false
    mode: 0644
  with_items: "{{ (php_56_cli_mods_present.keys() | list) + (php_56_cli_mods_absent.keys() | list) }}"
  tags:
    - configuration
    - php-56-cli
    - php-56-cli-mods-state
    - php-56-cli-mods-state-priorities
    - php-56-cli-mods-state-priorities-touch

- name: mods | get priorities  # noqa command-instead-of-module
  ansible.builtin.command: >
    sed -ne "s/^;[ ]\?priority=\([0-9]\+\)$/\\1/p" {{ php_56_cli_mods_available_path }}/{{ item }}.ini
  register: _php_56_cli_module_priorities
  changed_when: false
  with_items: "{{ (php_56_cli_mods_present.keys() | list) + (php_56_cli_mods_absent.keys() | list) }}"
  tags:
    - configuration
    - php-56-cli
    - php-56-cli-mods-state
    - php-56-cli-mods-state-priorities
    - php-56-cli-mods-state-priorities-get

- name: mods | disable
  ansible.builtin.command: >
    phpdismod -v {{ php_56_cli_version }} -s cli {{ item.item }}
  args:
    removes: "{{ php_56_cli_conf_d_file }}/{{ item.stdout | default(20, true) }}-{{ item.item }}.ini"
  with_items: "{{ _php_56_cli_module_priorities.results }}"
  when: item.item in php_56_cli_mods_absent.keys()
  tags:
    - configuration
    - php-56-cli
    - php-56-cli-mods-state
    - php-56-cli-mods-state-disable

- name: mods | enable
  ansible.builtin.command: >
    phpenmod -v {{ php_56_cli_version }} -s cli {{ item.item }}
  args:
    creates: "{{ php_56_cli_conf_d_file }}/{{ item.stdout | default(20, true) }}-{{ item.item }}.ini"
  with_items: "{{ _php_56_cli_module_priorities.results }}"
  when: item.item in php_56_cli_mods_present.keys()
  tags:
    - configuration
    - php-56-cli
    - php-56-cli-mods-state
    - php-56-cli-mods-state-enable
