# tasks file for php-56-cli
---
- name: mods | touch priorities
  copy:
    content: ''
    dest: "{{ php_56_cli_mods_available_path }}/{{ item.0 }}.ini"
    force: false
  with_flattened:
    - "{{ php_56_cli_mods_present | dictsort }}"
    - "{{ php_56_cli_mods_absent | dictsort }}"
  tags:
    - configuration
    - php-56-cli
    - php-56-cli-mods-state
    - php-56-cli-mods-state-get-priorities

- name: mods | get priorities
  command: sed -ne "s/^;[ ]\?priority=\([0-9]\+\)$/\\1/p" {{ php_56_cli_mods_available_path }}/{{ item.0 }}.ini
  register: php_56_cli_module_priorities
  changed_when: false
  with_flattened:
    - "{{ php_56_cli_mods_present | dictsort }}"
    - "{{ php_56_cli_mods_absent | dictsort }}"
  tags:
    - configuration
    - php-56-cli
    - php-56-cli-mods-state
    - php-56-cli-mods-state-get-priorities

- name: mods | disable
  command: phpdismod -v {{ php_56_cli_version }} -s cli {{ item.item.0 }}
  args:
    removes: "{{ php_56_cli_conf_d_file }}/{{ item.stdout | default(20, true) }}-{{ item.item.0 }}.ini"
  with_items: "{{ php_56_cli_module_priorities.results }}"
  when: item.item.0 in php_56_cli_mods_absent.keys()
  tags:
    - configuration
    - php-56-cli
    - php-56-cli-mods-state
    - php-56-cli-mods-state-disable

- name: mods | enable
  command: phpenmod -v {{ php_56_cli_version }} -s cli {{ item.item.0 }}
  args:
    creates: "{{ php_56_cli_conf_d_file }}/{{ item.stdout | default(20, true) }}-{{ item.item.0 }}.ini"
  with_items: "{{ php_56_cli_module_priorities.results }}"
  when: item.item.0 in php_56_cli_mods_present.keys()
  tags:
    - configuration
    - php-56-cli
    - php-56-cli-mods-state
    - php-56-cli-mods-state-enable
