# tasks file for php-56-cli
---
- name: repository
  apt_repository:
    repo: 'ppa:ondrej/php'
    update_cache: true
    mode: 0644
  tags:
    - configuration
    - php-56-cli
    - php-56-cli-repository
    - php-56-cli-repository-add
